default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root

development:
  <<: *default
  database: brew_development
  password:

test:
  <<: *default
  database: brew_test
  password:

production:
  <<: *default
  database: brew
  password:
